apiVersion: v1
data:
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::315860844598:role/dev-eks-cluster-node-group-role"
      "username": "system:node:{{EC2PrivateDNSName}}"
  mapUsers: |
    - userarn: arn:aws:iam::315860844598:user/root
      username: root
      groups:
        - system:masters
    - userarn: arn:aws:iam::315860844598:user/eks-admin-user
      username: eks-admin-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-23T07:39:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "36356"
  uid: 14ca7296-bcc1-46e7-8ac5-9c4adbd216c7
